[package]
name = "matrirc"
edition = "2021"
version = "0.1.0"
description = "An ircd to matrix gateway"
authors = ["Dominique Martinet <asmadeus@codewreck.org>"]
license = "WTFPLv2"
keywords = ["irc", "matrix"]
repository = "https://github.com/martinetd/matrirc"
readme = "README.md"

[dependencies]
env_logger = "0.10"
log = "0.4"
clap = { version = "4.3.0", features = ["derive"] }
irc = { version = "0.15", git = "https://github.com/aatxe/irc", rev = "3d037df761b4ec1da6811cc8481c18cfb2799dc7" }
anyhow = "1.0"
tokio = { version = "1.0.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"
zeroize = "1.6"
pwbox = "0.5"
rand_core = { version = "0.6", features = ["getrandom"] }
serde_json = "1.0"
serde = "1.0"
